#ifndef VERSION_CONTROL_H_
#define VERSION_CONTROL_H_

//版本号规则：V(VERSION_MAJOR).(VESION_MINOR)
#define VERSION_MAJOR 3
#define VERSION_MINOR 0.0

//用于记录对应机械臂软件版本号
#define VERSION_ROBOT_MARJOR 3
#define VERSION_ROBOT_MINOR 7.8


#endif